var annotated =
[
    [ "Dicom", "classDicom.html", "classDicom" ],
    [ "QtDcm", "classQtDcm.html", "classQtDcm" ],
    [ "QtDcmConvert", "classQtDcmConvert.html", "classQtDcmConvert" ],
    [ "QtDcmDcm2niiSettingsWidget", "classQtDcmDcm2niiSettingsWidget.html", "classQtDcmDcm2niiSettingsWidget" ],
    [ "QtDcmFindCallback", "classQtDcmFindCallback.html", "classQtDcmFindCallback" ],
    [ "QtDcmFindCallbackPrivate", "classQtDcmFindCallbackPrivate.html", "classQtDcmFindCallbackPrivate" ],
    [ "QtDcmFindDicomdir", "classQtDcmFindDicomdir.html", "classQtDcmFindDicomdir" ],
    [ "QtDcmFindDicomdirPrivate", "classQtDcmFindDicomdirPrivate.html", "classQtDcmFindDicomdirPrivate" ],
    [ "QtDcmFindScu", "classQtDcmFindScu.html", "classQtDcmFindScu" ],
    [ "QtDcmImage", "classQtDcmImage.html", "classQtDcmImage" ],
    [ "QtDcmImportWidget", "classQtDcmImportWidget.html", "classQtDcmImportWidget" ],
    [ "QtDcmLocalDicomSettingsWidget", "classQtDcmLocalDicomSettingsWidget.html", "classQtDcmLocalDicomSettingsWidget" ],
    [ "QtDcmManager", "classQtDcmManager.html", "classQtDcmManager" ],
    [ "QtDcmManagerPrivate", "classQtDcmManagerPrivate.html", "classQtDcmManagerPrivate" ],
    [ "QtDcmMoveDicomdir", "classQtDcmMoveDicomdir.html", "classQtDcmMoveDicomdir" ],
    [ "QtDcmMoveDicomdirPrivate", "classQtDcmMoveDicomdirPrivate.html", "classQtDcmMoveDicomdirPrivate" ],
    [ "QtDcmMoveScu", "classQtDcmMoveScu.html", "classQtDcmMoveScu" ],
    [ "QtDcmPatient", "classQtDcmPatient.html", "classQtDcmPatient" ],
    [ "QtDcmPreferences", "classQtDcmPreferences.html", "classQtDcmPreferences" ],
    [ "QtDcmPreferencesDialog", "classQtDcmPreferencesDialog.html", "classQtDcmPreferencesDialog" ],
    [ "QtDcmPreferencesPrivate", "classQtDcmPreferencesPrivate.html", "classQtDcmPreferencesPrivate" ],
    [ "QtDcmPreferencesWidget", "classQtDcmPreferencesWidget.html", "classQtDcmPreferencesWidget" ],
    [ "QtDcmPreviewWidget", "classQtDcmPreviewWidget.html", "classQtDcmPreviewWidget" ],
    [ "QtDcmPrivate", "classQtDcmPrivate.html", "classQtDcmPrivate" ],
    [ "QtDcmSerie", "classQtDcmSerie.html", "classQtDcmSerie" ],
    [ "QtDcmSerieInfoWidget", "classQtDcmSerieInfoWidget.html", "classQtDcmSerieInfoWidget" ],
    [ "QtDcmServer", "classQtDcmServer.html", "classQtDcmServer" ],
    [ "QtDcmServersDicomSettingsWidget", "classQtDcmServersDicomSettingsWidget.html", "classQtDcmServersDicomSettingsWidget" ],
    [ "QtDcmStoreScu", "classQtDcmStoreScu.html", "classQtDcmStoreScu" ],
    [ "QtDcmStudy", "classQtDcmStudy.html", "classQtDcmStudy" ]
];