set(CPACK_GENERATOR NSIS)
set(CPACK_NSIS_INSTALLED_ICON_NAME "QtDcm")
set(CPACK_NSIS_DISPLAY_NAME "QtDcm")
set(CPACK_NSIS_HELP_LINK "https://github.com/abadie/qtdcm")
set(CPACK_NSIS_URL_INFO_ABOUT "https://github.com/abadie/qtdcm")
set(CPACK_NSIS_CONTACT ${CPACK_PACKAGE_CONTACT})
set(CPACK_PACKAGE_INSTALL_DIRECTORY "QtDcm-${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}")

set(CPACK_NSIS_CREATE_ICONS "CreateShortCut '\$SMPROGRAMS\\\\$STARTMENU_FOLDER\\\\${PROJECT_NAME}.lnk' '\$INSTDIR\\\\bin\\\\dicom.exe'")
set(CPACK_NSIS_DELETE_ICONS "Delete '\$SMPROGRAMS\\\\$START_MENU\\\\${PROJECT_NAME}.lnk'")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut '\$DESKTOP\\\\${PROJECT_NAME}.lnk' '\$INSTDIR\\\\bin\\\\dicom.exe'")
set(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete '\$DESKTOP\\\\${PROJECT_NAME}.lnk'")

string(TOLOWER ${CMAKE_SYSTEM_PROCESSOR} BUILD_PROCESSOR)

if(BUILD_PACKAGE_BINARY)
  set(CPACK_PACKAGE_FILE_NAME "qtdcm-runtime-${BUILD_PROCESSOR}-${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}")
endif()

if(BUILD_PACKAGE_SDK)
  set(CPACK_PACKAGE_FILE_NAME "qtdcm-sdk-${BUILD_PROCESSOR}-${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}")
endif()
