set(BUILD_SHARED_LIBS CACHE FORCE "Build QtDCM with shared libraries." ON)
set(CPACK_GENERATOR ${CPACK_GENERATOR};DEB)
set(CPACK_DEB "ON")
if (BUILD_PACKAGE_BINARY)
  option(BUILD_PACKAGE_DEV "Package development distribution of QtDCM" OFF)
  set(CPACK_PACKAGE_NAME "qtdcm")
  set(CPACK_DEB_PACKAGE_DESCRIPTION "")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt4-gui (>=4.3)")
else (BUILD_PACKAGE_BINARY)
    option(BUILD_PACKAGE_BINARY "Package binary distribution of QtDCM" OFF)
    set(CPACK_PACKAGE_NAME "qtdcm-dev")
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "QtDCM provides widgets for DICOM support, This package is for development use")
    set(CPACK_PACKAGE_FILE_NAME "qtdcm-dev-${QTDCM_VERSION_MAJOR}.${QTDCM_VERSION_MINOR}.${QTDCM_VERSION_PATCH}")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "qtdcm (>=0.1), cmake (>=2.6)")
endif(BUILD_PACKAGE_BINARY)
