set(QTDCM_BINARY_INSTALL_DIR "${QTDCM_BINARY_DIR}/install")
make_directory(${QTDCM_BINARY_INSTALL_DIR})

#Installing cmake files
if ( NOT BUILD_PACKAGE OR BUILD_PACKAGE_DEV OR BUILD_PACKAGE_SDK)
  set(QTDCM_CMAKE_FILES
    ${QTDCM_BINARY_INSTALL_DIR}/QtDCMConfig.cmake
    ${QTDCM_BINARY_INSTALL_DIR}/UseQtDCM.cmake
    ${QTDCM_BINARY_INSTALL_DIR}/QtDCMBuildSettings.cmake
    ${QTDCM_BINARY_INSTALL_DIR}/QtDCMLibraryDepends.cmake
  )
  install_files(${INSTALL_CMAKE} FILES ${QTDCM_CMAKE_FILES})
endif( NOT BUILD_PACKAGE OR BUILD_PACKAGE_DEV OR BUILD_PACKAGE_SDK )

# Installing includes files
if ( NOT BUILD_PACKAGE OR BUILD_PACKAGE_DEV OR BUILD_PACKAGE_SDK )
  set(QTDCM_INCLUDE_FILES)
  foreach (inc ${QTDCM_INCLUDE_DIRS})
    file(GLOB QTDCM_INCLUDE_FILES_TMP "${inc}/*.h")
    file(GLOB QTDCM_INCLUDE_FILES_TMP2 "${inc}/*.txx")
    set(QTDCM_INCLUDE_FILES
      ${QTDCM_INCLUDE_FILES_TMP}
      ${QTDCM_INCLUDE_FILES_TMP2}
      ${QTDCM_INCLUDE_FILES}
    )
  endforeach (inc)
  install_files(${INSTALL_INC} FILES ${QTDCM_INCLUDE_FILES})
endif( NOT BUILD_PACKAGE OR BUILD_PACKAGE_DEV OR BUILD_PACKAGE_SDK)

#Config file for installation
set(QTDCM_INSTALL_DIR ${CMAKE_INSTALL_PREFIX})
set(QTDCM_CMAKE_DIR "${CMAKE_INSTALL_PREFIX}${INSTALL_CMAKE}")
set(QTDCM_BIN_DIR "${CMAKE_INSTALL_PREFIX}${INSTALL_BIN}")
set(QTDCM_INCLUDE_DIRS  "${CMAKE_INSTALL_PREFIX}${INSTALL_INC}")
set(QTDCM_CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}${INSTALL_CMAKE}")
if (WIN32 AND BUILD_SHARED_LIBS)
  set(QTDCM_LIBRARY_DIRS  "${CMAKE_INSTALL_PREFIX}${INSTALL_BIN}")
else(WIN32 AND BUILD_SHARED_LIBS)
  set(QTDCM_LIBRARY_DIRS  "${CMAKE_INSTALL_PREFIX}${INSTALL_LIB}")
endif(WIN32 AND BUILD_SHARED_LIBS)


SET(QTDCM_USE_FILE ${QTDCM_CMAKE_DIR}UseQtDCM.cmake)
SET(QTDCM_LIBRARY_DEPENDS_FILE ${QTDCM_CMAKE_DIR}QtDCMLibraryDepends.cmake)
SET(QTDCM_BUILD_SETTINGS_FILE ${QTDCM_CMAKE_DIR}QtDCMBuildSettings.cmake)

#Generate ViSTAL cmake file for external projects
cmake_export_build_settings(${QTDCM_BINARY_INSTALL_DIR}/QtDCMBuildSettings.cmake)
export_library_dependencies(${QTDCM_BINARY_INSTALL_DIR}/QtDCMLibraryDepends.cmake)
configure_file(${QTDCM_SOURCE_DIR}/CMake/QtDCMConfig.cmake.in ${QTDCM_BINARY_INSTALL_DIR}/QtDCMConfig.cmake)
configure_file(${QTDCM_SOURCE_DIR}/CMake/UseQtDCM.cmake.in ${QTDCM_BINARY_INSTALL_DIR}/UseQtDCM.cmake)
