# SETTING installation directories
SET (INSTALL_CMAKE /lib/QtDCM-${QTDCM_VERSION_MAJOR}.${QTDCM_VERSION_MINOR}/)
SET (INSTALL_BIN /bin/)
SET (INSTALL_LIB /lib/)
SET (INSTALL_INC /include/qtdcm)
SET (INSTALL_DOC /doc/)
SET (INSTALL_MAN /man/)
SET (INSTALL_SHARE /share/)

## SETTING THE INCLUDE DIRS
SET (QTDCM_INCLUDE_DIRS
## Modules include dirs
  ${QTDCM_SOURCE_DIR}/Code
)

## SETTING QTDCM LIBRARY DIRS
SET (QTDCM_LIBRARY_DIRS
  ${LIBRARY_OUTPUT_PATH}
)

include_directories(${QTDCM_INCLUDE_DIRS})
link_directories(${QTDCM_LIBRARY_DIRS})

## SETTING QTDCM LIBS
SET(QTDCM_LIBS
qtdcm
)
